name: PyPI Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install uv and Setup virtual environment
      run: |
        python3 -m ensurepip --upgrade
        python3 -m pip install uv
        uv venv .venv --python=3.12

    - name: Install dependencies and Build package
      run: |
        source .venv/bin/activate
        uv pip install --upgrade pip
        uv pip install build setuptools wheel
        uv build

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_KEY }}
      run: |
        source .venv/bin/activate
        uv pip install twine
        twine upload dist/*
